import{useEffect,useMemo,useState,type ReactNode}from'react';
export type Status='idle'|'running'|'complete'|'failed';
export const cx=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(' ');
export function Spinner({label='Working'}:{label?:string}){return <span className="al-spinner" role="status"><i aria-hidden="true"/>{label}</span>}
export function Thinking({summary='Thinking',children}:{summary?:string;children?:ReactNode}){return <details className="al-thinking"><summary><span className="al-shimmer">{summary}</span></summary>{children&&<div>{children}</div>}</details>}
export function ToolCall({name,status='running',meta}:{name:string;status?:Status;meta?:string}){return <div className="al-tool" data-status={status}><span className="al-status" aria-hidden="true"/><strong>{name}</strong>{meta&&<span>{meta}</span>}</div>}
export type Task={id:string;label:string;status:Status;detail?:string};
export function TaskList({title='Tasks',tasks}:{title?:string;tasks:Task[]}){const done=tasks.filter(x=>x.status==='complete').length;return <section className="al-tasklist"><header><strong>{title}</strong><span>{done}/{tasks.length}</span></header><ul>{tasks.map(t=><li key={t.id} data-status={t.status}><span className="al-status"/><div><strong>{t.label}</strong>{t.detail&&<small>{t.detail}</small>}</div></li>)}</ul></section>}
export function ApprovalCard({title,description,options,onSelect}:{title:string;description?:string;options:string[];onSelect?:(v:string)=>void}){return <section className="al-card al-approval"><h3>{title}</h3>{description&&<p>{description}</p>}<div>{options.map(x=><button key={x} onClick={()=>onSelect?.(x)}>{x}</button>)}</div></section>}
export function RecommendationCard({title,body,confidence='High confidence',onAccept,onReject}:{title:string;body:string;confidence?:string;onAccept?:()=>void;onReject?:()=>void}){return <section className="al-card"><span className="al-kicker">{confidence}</span><h3>{title}</h3><p>{body}</p><div className="al-actions"><button className="al-secondary" onClick={onReject}>Alternatives</button><button className="al-primary" onClick={onAccept}>Accept</button></div></section>}
export function SourceList({sources}:{sources:{title:string;url:string;domain?:string}[]}){return <ol className="al-sources">{sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer"><strong>{s.title}</strong><span>{s.domain??new URL(s.url).hostname}</span></a></li>)}</ol>}
export function ContextCard({title,kind,children,meta}:{title:string;kind:string;children:ReactNode;meta?:string}){return <article className="al-context"><header><span>{kind}</span>{meta&&<small>{meta}</small>}</header><h3>{title}</h3><div>{children}</div></article>}
export function CodeBlock({filename='code.ts',code}:{filename?:string;code:string}){const[copied,setCopied]=useState(false);async function copy(){await navigator.clipboard.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1200)}return <figure className="al-code"><figcaption><span>{filename}</span><button onClick={copy}>{copied?'Copied':'Copy'}</button></figcaption><pre>{code.split('\n').map((line,i)=><span key={i}><i>{i+1}</i><code>{line||' '}</code></span>)}</pre></figure>}
export type DiffLine={type:'add'|'remove'|'context';content:string;oldNumber?:number;newNumber?:number};
export function FileDiff({filename,lines}:{filename:string;lines:DiffLine[]}){return <figure className="al-diff"><figcaption>{filename}</figcaption><pre>{lines.map((l,i)=><span key={i} data-type={l.type}><i>{l.oldNumber??''}</i><i>{l.newNumber??''}</i><code>{l.type==='add'?'+':l.type==='remove'?'-':' '}{l.content}</code></span>)}</pre></figure>}
export function DataTable({columns,rows,caption}:{columns:string[];rows:(string|number|ReactNode)[][];caption?:string}){return <div className="al-table-wrap"><table className="al-table">{caption&&<caption>{caption}</caption>}<thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
export function FilterTable({columns,rows,statusColumn}:{columns:string[];rows:string[][];statusColumn:number}){const statuses=useMemo(()=>['All',...Array.from(new Set(rows.map(r=>r[statusColumn])))],[rows,statusColumn]);const[filter,setFilter]=useState('All');const shown=filter==='All'?rows:rows.filter(r=>r[statusColumn]===filter);return <section><div className="al-filters">{statuses.map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}<b>{s==='All'?rows.length:rows.filter(r=>r[statusColumn]===s).length}</b></button>)}</div><DataTable columns={columns} rows={shown}/></section>}
export function PromptBar({placeholder='Ask anything',onSubmit}:{placeholder?:string;onSubmit?:(v:string)=>void}){const[v,setV]=useState('');return <form className="al-prompt" onSubmit={e=>{e.preventDefault();if(v.trim()){onSubmit?.(v);setV('')}}}><label className="al-sr" htmlFor="al-prompt-input">Prompt</label><textarea id="al-prompt-input" value={v} onChange={e=>setV(e.target.value)} placeholder={placeholder} rows={1}/><button disabled={!v.trim()} aria-label="Send">↑</button></form>}
export function SearchCommand({items,onSelect}:{items:string[];onSelect?:(x:string)=>void}){const[q,setQ]=useState('');const results=items.filter(x=>x.toLowerCase().includes(q.toLowerCase()));return <div className="al-command"><label><span>Search</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Type a command"/></label><ul>{results.map(x=><li key={x}><button onClick={()=>onSelect?.(x)}>{x}</button></li>)}</ul>{!results.length&&<p>No matching commands</p>}</div>}
export function StreamText({text,speed=18}:{text:string;speed?:number}){const[n,setN]=useState(0);useEffect(()=>{setN(0);const id=setInterval(()=>setN(x=>{if(x>=text.length){clearInterval(id);return x}return x+1}),speed);return()=>clearInterval(id)},[text,speed]);return <p className="al-stream" aria-label={text}>{text.slice(0,n)}<span aria-hidden="true"/></p>}
export function ToolChips({items}:{items:{label:string;status?:Status}[]}){return <div className="al-chips">{items.map(x=><span key={x.label} data-status={x.status??'idle'}><i/>{x.label}</span>)}</div>}
export function ImageGeneration({src,prompt,status='complete'}:{src?:string;prompt:string;status?:Status}){return <figure className="al-imagegen" data-status={status}>{src?<img src={src} alt={prompt}/>:<div className="al-image-placeholder"/>}<figcaption><span>{status==='running'?'Generating':'Generated'}</span><q>{prompt}</q></figcaption></figure>}
